# Docker Compose using pre-built images from GitHub Container Registry
# Usage: docker compose -f compose.ghcr.yml up -d

services:
  mongo:
    image: mongo:8
    container_name: uptimer-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/mortenoh/uptimer:main
    container_name: uptimer-api
    ports:
      - "8000:8000"
    environment:
      - UPTIMER_MONGODB_URI=mongodb://mongo:27017
      - UPTIMER_MONGODB_DB=uptimer
      - UPTIMER_HOST=0.0.0.0
      - UPTIMER_PORT=8000
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: ghcr.io/mortenoh/uptimer-frontend:main
    container_name: uptimer-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  mongo_data:
